import logging
import re

from telegram import (
    Update,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
)

from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    ContextTypes,
    filters,
)

from backend.services.config import TELEGRAM_BOT_TOKEN
from backend.services.rag_service import answer_question
from backend.services.telegram_notifier import register_subscriber
from backend.database.supabase_database import supabase


# ============================================================
# LOGGING
# ============================================================

logging.basicConfig(
    level=logging.INFO,
)

logger = logging.getLogger(__name__)


# ============================================================
# TELEGRAM SESSION
# ============================================================

def set_active_paper(chat_id, paper_id):
    """
    Store the paper currently selected by a Telegram user.
    """

    (
        supabase
        .table("telegram_sessions")
        .upsert(
            {
                "chat_id": chat_id,
                "paper_id": paper_id,
            },
            on_conflict="chat_id",
        )
        .execute()
    )


def get_active_paper(chat_id):
    """
    Retrieve the paper currently selected by a Telegram user.
    """

    response = (
        supabase
        .table("telegram_sessions")
        .select("paper_id")
        .eq("chat_id", chat_id)
        .limit(1)
        .execute()
    )

    if not response.data:
        return None

    return response.data[0].get("paper_id")


# ============================================================
# SOURCE FORMATTING
# ============================================================

def format_sources(sources):
    """
    Convert RAG source metadata into a readable Telegram message.
    """

    if not sources:
        return ""

    lines = []
    seen = set()

    for source in sources:

        key = (
            source.get("section"),
            source.get("subsection"),
            source.get("page_start"),
            source.get("page_end"),
        )

        if key in seen:
            continue

        seen.add(key)

        section = source.get("section") or "Unknown"

        subsection = source.get("subsection")

        if subsection:
            section += f" → {subsection}"

        page_start = source.get("page_start")
        page_end = source.get("page_end")

        if page_start and page_end:

            if page_start == page_end:
                pages = f"p. {page_start}"
            else:
                pages = f"pp. {page_start}–{page_end}"

            lines.append(
                f"• {section} ({pages})"
            )

        elif page_start:

            lines.append(
                f"• {section} (p. {page_start})"
            )

        else:

            lines.append(
                f"• {section}"
            )

    if not lines:
        return ""

    return (
        "Sources:\n"
        + "\n".join(lines)
    )


# ============================================================
# CLEAN GEMINI ANSWER
# ============================================================

def clean_llm_answer(text):
    """
    Remove internal source markers generated by the RAG prompt.
    """

    if not text:
        return ""

    # Remove markers such as:
    # [SOURCE 1]
    # [SOURCE 1, SOURCE 2]

    text = re.sub(
        r"\[SOURCE\s+\d+(?:\s*,\s*SOURCE\s+\d+)*\]",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # Remove an existing Sources section.
    text = re.sub(
        r"\n+\s*Sources:\s*(?:\n[-•].*)*$",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # Remove trailing spaces before newlines.
    text = re.sub(
        r"[ \t]+\n",
        "\n",
        text,
    )

    # Avoid excessive blank lines.
    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    )

    return text.strip()


# ============================================================
# LONG TELEGRAM MESSAGE HANDLER
# ============================================================

async def send_long_message(message, text):
    """
    Telegram messages have a character limit.
    Split long RAG answers safely.
    """

    if not text:
        return

    max_length = 4000

    if len(text) <= max_length:

        await message.reply_text(text)

        return

    parts = []

    while text:

        if len(text) <= max_length:

            parts.append(text)

            break

        split_at = text.rfind(
            "\n",
            0,
            max_length,
        )

        if split_at <= 0:

            split_at = max_length

        parts.append(
            text[:split_at]
        )

        text = text[split_at:].lstrip()

    for part in parts:

        await message.reply_text(part)


# ============================================================
# /START
# ============================================================

async def start(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    """
    Register the Telegram user for paper notifications.
    """

    chat = update.effective_chat
    user = update.effective_user

    if not chat:
        return

    try:

        register_subscriber(
            chat_id=chat.id,
            username=(
                user.username
                if user
                else None
            ),
            first_name=(
                user.first_name
                if user
                else None
            ),
        )

        if update.message:

            await update.message.reply_text(
                "🔬 ResearchX AI\n\n"
                "✅ You are now registered for new AI "
                "research paper notifications.\n\n"
                "When a new paper arrives, tap "
                "📖 Ask about this paper to start asking "
                "questions about it.\n\n"
                "You can also use /papers to browse "
                "previous papers."
            )

    except Exception:

        logger.exception(
            "Subscriber registration failed"
        )

        if update.message:

            await update.message.reply_text(
                "🔬 ResearchX AI\n\n"
                "I couldn't register you for notifications "
                "right now.\n\n"
                "Please try /start again."
            )


# ============================================================
# /PAPERS
# ============================================================

async def papers(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    """
    Display previously ingested research papers.
    """

    if not update.message:
        return

    try:

        response = (
            supabase
            .table("papers")
            .select(
                "paper_id,title,created_at"
            )
            .order(
                "created_at",
                desc=True,
            )
            .limit(50)
            .execute()
        )

        papers_data = response.data or []

        if not papers_data:

            await update.message.reply_text(
                "📚 No papers are currently ingested."
            )

            return

        keyboard = []

        for paper in papers_data:

            paper_id = paper.get(
                "paper_id"
            )

            title = paper.get(
                "title",
                "Untitled paper",
            )

            if not paper_id:
                continue

            keyboard.append(
                [
                    InlineKeyboardButton(
                        text=f"📖 {title}",
                        callback_data=(
                            f"paper:{paper_id}"
                        ),
                    )
                ]
            )

        if not keyboard:

            await update.message.reply_text(
                "📚 No selectable papers found."
            )

            return

        reply_markup = InlineKeyboardMarkup(
            keyboard
        )

        await update.message.reply_text(
            "📚 Your Research Papers\n\n"
            "Tap a paper to select it and start "
            "asking questions:",
            reply_markup=reply_markup,
        )

    except Exception as exc:

        logger.exception(
            "Failed to retrieve papers"
        )

        await update.message.reply_text(
            "Sorry, I couldn't retrieve the "
            "paper list right now.\n\n"
            f"Error: {exc}"
        )


# ============================================================
# PAPER SELECTION
# ============================================================

async def select_paper(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    """
    Handle the button used to select a paper.
    """

    query = update.callback_query

    if not query:
        return

    await query.answer()

    data = query.data or ""

    if not data.startswith("paper:"):
        return

    paper_id = data[
        len("paper:"):
    ].strip()

    if not paper_id:

        if query.message:

            await query.message.reply_text(
                "❌ Invalid paper selection."
            )

        return

    chat = update.effective_chat

    if not chat:
        return

    chat_id = chat.id

    # --------------------------------------------------------
    # Verify that the selected paper exists.
    # --------------------------------------------------------

    try:

        response = (
            supabase
            .table("papers")
            .select(
                "paper_id,title"
            )
            .eq(
                "paper_id",
                paper_id,
            )
            .limit(1)
            .execute()
        )

        if not response.data:

            if query.message:

                await query.message.reply_text(
                    "❌ This paper could not be found."
                )

            return

        paper = response.data[0]

    except Exception:

        logger.exception(
            "Failed to verify selected paper"
        )

        if query.message:

            await query.message.reply_text(
                "❌ I couldn't verify that paper right now."
            )

        return

    # --------------------------------------------------------
    # Save selected paper in Supabase.
    # --------------------------------------------------------

    try:

        set_active_paper(
            chat_id,
            paper_id,
        )

        logger.info(
            "Selected paper for chat %s: %s",
            chat_id,
            paper_id,
        )

    except Exception:

        logger.exception(
            "Failed to store Telegram session"
        )

        if query.message:

            await query.message.reply_text(
                "❌ I couldn't save your paper selection "
                "right now. Please try again."
            )

        return

    # --------------------------------------------------------
    # Confirm selection.
    # --------------------------------------------------------

    if query.message:

        await query.message.reply_text(
            "✅ Paper selected!\n\n"
            f"📖 {paper['title']}\n\n"
            "You can now ask me anything about this paper."
        )


# ============================================================
# NATURAL LANGUAGE QUESTION
# ============================================================

async def question(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    """
    Handle arbitrary questions about the selected paper.
    """

    if not update.message:
        return

    chat = update.effective_chat

    if not chat:
        return

    chat_id = chat.id

    # --------------------------------------------------------
    # Get currently selected paper.
    # --------------------------------------------------------

    try:

        paper_id = get_active_paper(
            chat_id
        )

    except Exception:

        logger.exception(
            "Failed to retrieve Telegram session"
        )

        await update.message.reply_text(
            "Sorry, I couldn't retrieve your selected "
            "paper right now.\n\n"
            "Please select the paper again using /papers."
        )

        return

    # --------------------------------------------------------
    # No paper selected.
    # --------------------------------------------------------

    if not paper_id:

        await update.message.reply_text(
            "📖 Please select a paper first.\n\n"
            "Use /papers and tap the paper you "
            "want to ask about."
        )

        return

    # --------------------------------------------------------
    # Get user's question.
    # --------------------------------------------------------

    q = (
        update.message.text or ""
    ).strip()

    if not q:
        return

    # --------------------------------------------------------
    # Show processing message.
    # --------------------------------------------------------

    processing_message = (
        await update.message.reply_text(
            "🔎 Searching the paper and "
            "generating an answer..."
        )
    )

    logger.info(
        "Question from chat %s | paper=%s | question=%s",
        chat_id,
        paper_id,
        q,
    )

    # --------------------------------------------------------
    # RAG + Gemini.
    # --------------------------------------------------------

    try:

        result = answer_question(
            q,
            paper_id,
        )

        # ----------------------------------------------------
        # Clean generated answer.
        # ----------------------------------------------------

        text = clean_llm_answer(
            result.get(
                "answer",
                "",
            )
        )

        # ----------------------------------------------------
        # Format sources.
        # ----------------------------------------------------

        sources = format_sources(
            result.get(
                "sources",
                [],
            )
        )

        # ----------------------------------------------------
        # Add sources to final answer.
        # ----------------------------------------------------

        if sources:

            text = re.sub(
                r"\n+\s*Sources:\s*(?:\n[-•].*)*$",
                "",
                text,
                flags=re.IGNORECASE,
            ).strip()

            text = (
                f"{text}\n\n"
                f"{sources}"
            )

        # ----------------------------------------------------
        # Fallback answer.
        # ----------------------------------------------------

        if not text:

            text = (
                "I could not generate an answer "
                "from the retrieved paper context."
            )

        # ----------------------------------------------------
        # Send answer.
        # ----------------------------------------------------

        await send_long_message(
            update.message,
            text,
        )

        # ----------------------------------------------------
        # Remove processing message.
        # ----------------------------------------------------

        try:

            await processing_message.delete()

        except Exception:

            pass

    except Exception as exc:

        logger.exception(
            "RAG error"
        )

        try:

            await processing_message.delete()

        except Exception:

            pass

        await update.message.reply_text(
            "Sorry, I couldn't complete "
            "that request.\n\n"
            f"Error: {exc}"
        )


# ============================================================
# BUILD TELEGRAM APPLICATION
# ============================================================

def build_application():
    """
    Create the Telegram application and register handlers.

    IMPORTANT:
    This function does NOT start polling.
    FastAPI will manage the Telegram application
    lifecycle because we are using webhook mode.
    """

    if not TELEGRAM_BOT_TOKEN:

        raise RuntimeError(
            "TELEGRAM_BOT_TOKEN is not configured."
        )

    app = (
        Application
        .builder()
        .token(TELEGRAM_BOT_TOKEN)
        .build()
    )

    # --------------------------------------------------------
    # /start
    # --------------------------------------------------------

    app.add_handler(
        CommandHandler(
            "start",
            start,
        )
    )

    # --------------------------------------------------------
    # /papers
    # --------------------------------------------------------

    app.add_handler(
        CommandHandler(
            "papers",
            papers,
        )
    )

    # --------------------------------------------------------
    # Paper selection button
    # --------------------------------------------------------

    app.add_handler(
        CallbackQueryHandler(
            select_paper,
            pattern=r"^paper:",
        )
    )

    # --------------------------------------------------------
    # Natural-language questions
    # --------------------------------------------------------

    app.add_handler(
        MessageHandler(
            filters.TEXT
            & ~filters.COMMAND,
            question,
        )
    )

    return app


# ============================================================
# PROCESS TELEGRAM WEBHOOK UPDATE
# ============================================================

async def handle_update(
    telegram_app,
    update_data,
):
    """
    Convert Telegram JSON into a python-telegram-bot Update
    and pass it to the registered handlers.
    """

    update = Update.de_json(
        update_data,
        telegram_app.bot,
    )

    if update is None:
        return

    await telegram_app.process_update(
        update
    )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    print(
        "ResearchX AI Telegram bot is configured "
        "for webhook mode."
    )

    print(
        "Use backend.app to start the FastAPI server."
    )