import logging
import re

from telegram import (
    Update,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
)

from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    ContextTypes,
    filters,
)

from backend.services.config import TELEGRAM_BOT_TOKEN
from backend.services.rag_service import answer_question
from backend.services.telegram_notifier import register_subscriber
from backend.database.supabase_database import supabase


# ============================================================
# LOGGING
# ============================================================

logging.basicConfig(
    level=logging.INFO,
)


# ============================================================
# ACTIVE PAPER
# ============================================================

# Stores the currently selected paper for each Telegram chat.
#
# Example:
#
# {
#     123456789: "2609.11900v1"
# }
#
# This is kept in memory and resets when the bot restarts.
#
# NOTE:
# For the final online deployment, this should be moved to
# the telegram_sessions table in Supabase so the selected
# paper survives bot restarts.
ACTIVE_PAPER = {}


# ============================================================
# SOURCE FORMATTING
# ============================================================

def format_sources(sources):
    """
    Format structured sources for Telegram.

    Sources come from the actual retrieved chunks.
    They are generated by Python from the RAG retrieval results.
    """

    if not sources:
        return ""

    lines = []
    seen = set()

    for source in sources:

        key = (
            source.get("section"),
            source.get("subsection"),
            source.get("page_start"),
            source.get("page_end"),
        )

        # Avoid duplicate sources.
        if key in seen:
            continue

        seen.add(key)

        section = (
            source.get("section")
            or "Unknown"
        )

        if source.get("subsection"):
            section += (
                f" → "
                f"{source['subsection']}"
            )

        page_start = source.get(
            "page_start"
        )

        page_end = source.get(
            "page_end"
        )

        if page_start and page_end:

            if page_start == page_end:
                pages = f"p. {page_start}"

            else:
                pages = (
                    f"pp. "
                    f"{page_start}–"
                    f"{page_end}"
                )

            lines.append(
                f"• {section} ({pages})"
            )

        elif page_start:

            lines.append(
                f"• {section} "
                f"(p. {page_start})"
            )

        else:

            lines.append(
                f"• {section}"
            )

    if not lines:
        return ""

    return (
        "Sources:\n"
        + "\n".join(lines)
    )


# ============================================================
# CLEAN LLM CITATIONS
# ============================================================

def clean_llm_answer(text):
    """
    Remove source references generated by the LLM.

    The LLM may produce:

        [SOURCE 1]

    or:

        [SOURCE 1, SOURCE 2]

    Python generates the authoritative source list
    separately from the retrieved RAG chunks.
    """

    if not text:
        return ""

    # --------------------------------------------------------
    # Remove:
    #
    # [SOURCE 1]
    # [SOURCE 1, SOURCE 2]
    # --------------------------------------------------------

    text = re.sub(
        r"\[SOURCE\s+\d+(?:\s*,\s*SOURCE\s+\d+)*\]",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # Remove a Sources section generated by the LLM.
    # Python will generate the authoritative sources.
    # --------------------------------------------------------

    text = re.sub(
        r"\n+\s*Sources:\s*"
        r"(?:\n[-•].*)*$",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # Clean excessive whitespace.
    # --------------------------------------------------------

    text = re.sub(
        r"[ \t]+\n",
        "\n",
        text,
    )

    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    )

    return text.strip()


# ============================================================
# /START
# ============================================================

async def start(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    """
    Register the Telegram user for proactive notifications.
    """

    chat = update.effective_chat
    user = update.effective_user

    try:

        register_subscriber(
            chat_id=chat.id,
            username=(
                user.username
                if user
                else None
            ),
            first_name=(
                user.first_name
                if user
                else None
            ),
        )

        await update.message.reply_text(
            "🔬 ResearchX AI\n\n"
            "✅ You are now registered for new AI "
            "research paper notifications.\n\n"
            "When a new paper arrives, tap "
            "📖 Ask about this paper to start asking "
            "questions about it.\n\n"
            "You can also use /papers to browse "
            "previous papers."
        )

    except Exception:

        logging.exception(
            "Subscriber registration failed"
        )

        await update.message.reply_text(
            "🔬 ResearchX AI\n\n"
            "I couldn't register you for notifications "
            "right now.\n"
            "Please try /start again."
        )


# ============================================================
# /PAPERS
# ============================================================

async def papers(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    """
    Display previously ingested papers as clickable
    Telegram buttons.

    The user does not need to remember paper numbers.
    """

    try:

        response = (
            supabase
            .table("papers")
            .select(
                "paper_id,title,created_at"
            )
            .order(
                "created_at",
                desc=True,
            )
            .limit(50)
            .execute()
        )

        papers_data = (
            response.data
            or []
        )

        if not papers_data:

            await update.message.reply_text(
                "📚 No papers are currently ingested."
            )

            return

        # ----------------------------------------------------
        # Create clickable buttons.
        # ----------------------------------------------------

        keyboard = []

        for paper in papers_data:

            paper_id = paper.get(
                "paper_id"
            )

            title = paper.get(
                "title",
                "Untitled paper",
            )

            if not paper_id:
                continue

            # Telegram callback_data has a size limit.
            # arXiv paper IDs are short enough.

            keyboard.append(
                [
                    InlineKeyboardButton(
                        text=f"📖 {title}",
                        callback_data=(
                            f"paper:{paper_id}"
                        ),
                    )
                ]
            )

        if not keyboard:

            await update.message.reply_text(
                "📚 No selectable papers found."
            )

            return

        reply_markup = (
            InlineKeyboardMarkup(
                keyboard
            )
        )

        await update.message.reply_text(
            "📚 Your Research Papers\n\n"
            "Tap a paper to select it and start "
            "asking questions:",
            reply_markup=reply_markup,
        )

    except Exception as exc:

        logging.exception(
            "Failed to retrieve papers"
        )

        await update.message.reply_text(
            "Sorry, I couldn't retrieve the "
            "paper list right now.\n"
            f"Error: {exc}"
        )


# ============================================================
# PAPER SELECTION CALLBACK
# ============================================================

async def select_paper(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    """
    Handle clicks on paper buttons.

    Example callback_data:

        paper:2609.11900v1

    The selected paper becomes the active paper
    for the current Telegram chat.
    """

    query = update.callback_query

    if not query:
        return

    await query.answer()

    data = query.data or ""

    if not data.startswith("paper:"):
        return

    paper_id = data[
        len("paper:"):
    ].strip()

    if not paper_id:

        await query.message.reply_text(
            "❌ Invalid paper selection."
        )

        return

    chat_id = (
        update.effective_chat.id
    )

    # --------------------------------------------------------
    # Verify that the paper actually exists.
    # --------------------------------------------------------

    try:

        response = (
            supabase
            .table("papers")
            .select(
                "paper_id,title"
            )
            .eq(
                "paper_id",
                paper_id,
            )
            .limit(1)
            .execute()
        )

        if not response.data:

            await query.message.reply_text(
                "❌ This paper could not be found."
            )

            return

        paper = response.data[0]

    except Exception:

        logging.exception(
            "Failed to verify selected paper"
        )

        await query.message.reply_text(
            "❌ I couldn't verify that paper right now."
        )

        return

    # --------------------------------------------------------
    # Store active paper.
    # --------------------------------------------------------

    ACTIVE_PAPER[
        chat_id
    ] = paper_id

    logging.info(
        "Selected paper for chat %s: %s",
        chat_id,
        paper_id,
    )

    # --------------------------------------------------------
    # Confirm selection.
    # --------------------------------------------------------

    await query.message.reply_text(
        "✅ Paper selected!\n\n"
        f"📖 {paper['title']}\n\n"
        "You can now ask me anything about this paper."
    )


# ============================================================
# QUESTION HANDLER
# ============================================================

async def question(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
):
    """
    Answer an arbitrary natural-language question
    about the currently selected paper.
    """

    chat_id = (
        update.effective_chat.id
    )

    # --------------------------------------------------------
    # Get selected paper.
    # --------------------------------------------------------

    paper_id = ACTIVE_PAPER.get(
        chat_id
    )

    # --------------------------------------------------------
    # No paper selected.
    # --------------------------------------------------------

    if not paper_id:

        await update.message.reply_text(
            "📖 Please select a paper first.\n\n"
            "Use /papers and tap the paper you "
            "want to ask about."
        )

        return

    # --------------------------------------------------------
    # Get user question.
    # --------------------------------------------------------

    q = (
        update.message.text
        or ""
    ).strip()

    if not q:
        return

    # --------------------------------------------------------
    # Show processing message.
    # --------------------------------------------------------

    processing_message = (
        await update.message.reply_text(
            "🔎 Searching the paper and "
            "generating an answer..."
        )
    )

    logging.info(
        "Question from chat %s | paper=%s | question=%s",
        chat_id,
        paper_id,
        q,
    )

    try:

        # ====================================================
        # RAG
        # ====================================================

        result = answer_question(
            q,
            paper_id,
        )

        # ====================================================
        # CLEAN LLM ANSWER
        # ====================================================

        text = clean_llm_answer(
            result.get(
                "answer",
                "",
            )
        )

        # ====================================================
        # BUILD SOURCES
        # ====================================================

        sources = format_sources(
            result.get(
                "sources",
                [],
            )
        )

        # ====================================================
        # FINAL RESPONSE
        # ====================================================

        if sources:

            text = re.sub(
                r"\n+\s*Sources:\s*"
                r"(?:\n[-•].*)*$",
                "",
                text,
                flags=re.IGNORECASE,
            ).strip()

            text = (
                f"{text}\n\n"
                f"{sources}"
            )

        # ----------------------------------------------------
        # Fallback
        # ----------------------------------------------------

        if not text:

            text = (
                "I could not generate an answer "
                "from the retrieved paper context."
            )

        # ----------------------------------------------------
        # Send answer.
        # ----------------------------------------------------

        await update.message.reply_text(
            text
        )

        # ----------------------------------------------------
        # Remove processing message.
        # ----------------------------------------------------

        try:

            await processing_message.delete()

        except Exception:

            pass

    except Exception as exc:

        logging.exception(
            "RAG error"
        )

        try:

            await processing_message.delete()

        except Exception:

            pass

        await update.message.reply_text(
            "Sorry, I couldn't complete "
            "that request.\n"
            f"Error: {exc}"
        )


# ============================================================
# BUILD TELEGRAM APPLICATION
# ============================================================

def build_application():
    """
    Build and configure the Telegram application.
    """

    if not TELEGRAM_BOT_TOKEN:

        raise RuntimeError(
            "TELEGRAM_BOT_TOKEN is not configured."
        )

    app = (
        Application
        .builder()
        .token(
            TELEGRAM_BOT_TOKEN
        )
        .build()
    )

    # --------------------------------------------------------
    # /start
    # --------------------------------------------------------

    app.add_handler(
        CommandHandler(
            "start",
            start,
        )
    )

    # --------------------------------------------------------
    # /papers
    # --------------------------------------------------------

    app.add_handler(
        CommandHandler(
            "papers",
            papers,
        )
    )

    # --------------------------------------------------------
    # Paper button clicks.
    # --------------------------------------------------------

    app.add_handler(
        CallbackQueryHandler(
            select_paper,
            pattern=r"^paper:",
        )
    )

    # --------------------------------------------------------
    # Normal text questions.
    # --------------------------------------------------------

    app.add_handler(
        MessageHandler(
            filters.TEXT
            & ~filters.COMMAND,
            question,
        )
    )

    return app


# ============================================================
# START BOT
# ============================================================

if __name__ == "__main__":

    print(
        "ResearchX AI Telegram bot starting..."
    )

    app = build_application()

    app.run_polling()